//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeMart
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleProduct
    {
        public int Id { get; set; }
        public Nullable<int> Sale { get; set; }
        public Nullable<int> Product { get; set; }
    
        public virtual Product Product1 { get; set; }
        public virtual Sale Sale1 { get; set; }
    }
}
